# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.formbuilder:
        class: AppBundle\Utils\Formbuilder
        arguments: ["@doctrine.orm.entity_manager"]
    app.validation:
        class: AppBundle\Utils\Validation
        arguments: ["@doctrine.orm.entity_manager"]
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.services:
        class: AppBundle\Utils\Services
        arguments: ["@doctrine.orm.entity_manager"]
    app.login_success_handler:
        class: AppBundle\Utils\LoginSuccessHandler
        arguments: ["@doctrine.orm.entity_manager"]
