AppBundle\Entity\Ddfields:
    type: entity
    table: ddfields
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        objectName:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: object_name
        tableName:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: table_name
        colName:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: col_name
        colCode:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: col_code
        colLabel:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: col_label
        dataType:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: data_type
        dataSource:
            type: string
            nullable: false
            length: 1000
            options:
                fixed: false
            column: data_source
        valueDefault:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: value_default
        colPosition:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: col_position
        valueReadonly:
            type: boolean
            nullable: true
            column: value_readonly
        triggerUrl:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: trigger_url
        triggerTarget:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: trigger_target
        valueMaxlength:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: value_maxlength
        colActive:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: col_active
        searchOpt:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: search_opt
        zero:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        sysdate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        hidden:
            type: boolean
            nullable: true
        attributes:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
    lifecycleCallbacks: {  }
