AppBundle\Entity\Member:
    type: entity
    table: member
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        idno:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        birthdayday:
            type: boolean
            nullable: true
        birthdaymonth:
            type: boolean
            nullable: true
        birthdayyear:
            type: smallint
            nullable: true
            options:
                unsigned: false
        createdtime:
            type: integer
            nullable: true
            options:
                unsigned: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        level:
            type: smallint
            nullable: true
            options:
                unsigned: false
        membersince:
            type: integer
            nullable: true
            options:
                unsigned: false
        memberto:
            type: integer
            nullable: true
            options:
                unsigned: false
        sysdate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        administrators:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
