AppBundle\Entity\Newtable:
    type: entity
    table: newtable
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        number:
            type: integer
            nullable: true
            options:
                unsigned: false
        sysdate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        iddate:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
