AppBundle\Entity\Package:
    type: entity
    table: package
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
            options:
                default: '1'
        price:
            type: integer
            nullable: false
            options:
                unsigned: true
        createdby:
            type: integer
            nullable: true
            options:
                unsigned: false
        updatedby:
            type: integer
            nullable: true
            options:
                unsigned: false
        createdtime:
            type: integer
            nullable: true
            options:
                unsigned: false
        updatedtime:
            type: integer
            nullable: true
            options:
                unsigned: false
        sysdate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        maxhours:
            type: integer
            nullable: true
            options:
                unsigned: false
        maxvisitors:
            type: integer
            nullable: true
            options:
                unsigned: false
        maxdays:
            type: integer
            nullable: true
            options:
                unsigned: false
        maxprintpapers:
            type: integer
            nullable: true
            options:
                unsigned: false
        maxmeetinghours:
            type: integer
            nullable: true
            options:
                unsigned: false
        maxvisitorhours:
            type: integer
            nullable: true
            options:
                unsigned: false
        allowcredit:
            type: boolean
            nullable: false
            options:
                default: '0'
    lifecycleCallbacks: {  }
