AppBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nameEn:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: name_en
        nameVi:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: name_vi
        unit:
            type: integer
            nullable: false
            options:
                unsigned: false
        type:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
        category:
            type: integer
            nullable: false
            options:
                unsigned: false
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        showinbar:
            type: boolean
            nullable: false
            options:
                default: '1'
        startDate:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: start_date
        endDate:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: end_date
    lifecycleCallbacks: {  }
