AppBundle\Entity\ProductCategory:
    type: entity
    table: product_category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        code:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        weight:
            type: decimal
            nullable: false
            precision: 11
            scale: 5
        depth:
            type: integer
            nullable: false
            options:
                unsigned: false
        parentId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: parent_id
    lifecycleCallbacks: {  }
